### ISSUE TITLE
Size of qrcode is not fixed when data string is different

### ISSUE THREAD

**Issue by id1945** [kozakdenys/qr-code-styling#104]

**Comment by SamSamskies** [comment]
I also ran into this issue.

**Comment by ritute** [comment]
+1

**Comment by todor0v** [comment]
+1

**Comment by id1945** [comment]
@ezodnem It seems that this library has been orphaned and there is no one to take care of it anymore. :'(

**Comment by hawkerboy7** [comment]
Hi, this behavior I believe is expected.
Please see below why.

Lets say you have a 300x300 pixel canvas to show the QR-code in.
Each "dot" in the qr-code takes up a certain amount of space (with this library you can let some dots render as lines as well but the concept still applies).
Lets say 15x15 pixels including margins between the dots.
This means you have a grid of 300/15 = 20x20 dots.
Within that grid your data is represented.

Now you increase the amount of data.
At some point you will need a bigger grid to represent all the data since 20x20 is not big enough anymore.
So the library goes to the next grid which has enough space: 21x21.
This means your dots would need to be 300/21 ≈ 14,29 -> 14,29x14,29 pixels to nicely fill the 300x300 canvas.
This is an issue because if you want your qr-code to be a sharp image you must avoid [rendering lines "between" pixels](https://blog.coderfy.io/avoiding-blurry-lines-when-drawing-to-the-canvas)

So instead "dots" become 14x14 pixels.
The width and height now becomes: 14x21 = 294 pixels
This leaves a margin around the image of (300-294)/2 = 3 pixels.
This is the change in size.

@ezodnem changing the errorCorrectionLevel to "M" in your case probably made the required grid more suitable for your data range, meaning for all the different data inputs you provided the same grid could be used to represent the data.

This "issue" of changing the grid size and thus the dimensions of the qr-code should become less and less the more data you have since the ever increasing grid will be able to represent more data without needing to go to a bigger grid.
But I am not sure of this though... 

Maybe there is an option to force "dots" not to be whole integers and render a more blurry qr-code that fully respects the set size of the canvas.
Though I don't think this would be preferable in any situation..


Hopefully this helps somewhat in understanding the cause.

**Comment by kozakdenys** [comment]
@hawkerboy7 thank you, it is a correct explanation! If the size of dots is not integer, it usually causes the problem with gaps between dots.
![377408205-dd2961be-7ceb-46cc-a585-1adb8ffea3ac](https://github.com/user-attachments/assets/5056881a-72ae-42ab-a477-62c8dab2ead7)
It was intentional to make all sizes as integers to prevent gaps, but in this case, an extra margin may appear.
But in the version [v1.8.0](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.8.0) was added new property `dotOptions.roundSize`. If `false` it adds [shape-rendering="crispEdges"](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering#crispedges). It removes extra margin but it will look a little bit "crispy".

**Comment by SamSamskies** [comment]
@kozakdenys I'm using v1.9.1 and it still has some gaps when setting `dotOptions.roundSize` to `false`.

![Image](https://github.com/user-attachments/assets/f5d1acd2-1e37-4ccf-80c2-4c557a9eb8e6)

here's the options that i'm using:
```
{
        width: 300,
        height: 300,
        data: 'https://example.com',
        type: 'svg',
        margin: 32,
        dotsOptions: {
          roundSize: false,
          type: 'rounded',
        },
        cornersSquareOptions: {
          type: 'extra-rounded',
        },
        cornersDotOptions: {
          type: 'rounded',
        },
      }
```

**Comment by nikitaeverywhere** [comment]
This is an absolute blocker for us - sizes must be consistent if the lib provides `size` option. it reproduces even on your demo page when you make URL larger, and it's always random size. How can you build UI where QR code is random-sized.

<img width="1005" height="336" alt="Image" src="https://github.com/user-attachments/assets/18532cc5-41d2-4f3d-8731-a97d195b61ad" />
