### ISSUE TITLE
Glad you are back, but have concerns.

### ISSUE THREAD

**Issue by NickStull** [kozakdenys/qr-code-styling#223]
Welcome back. 

Ignoring this package for >2 years to then add paid plugins as the first thing does not inspire confidence in this project. 

To be clear... I have no issues supporting this project. In fact I have tried reaching out in the past via DM and email offering to financially support and got zero response. This along with closing some PRs with feature adds without a comment as to why is really concerning. Some transparency as to why these decisions were made would be nice. Thank you.

**Comment by NickStull** [comment]
Also @kozakdenys just fyi, I commented on PR #110 a while back. I see you merged it, but this is not a proper fix. This still results in some phones (android phones mostly) not being able to scan QR codes using this package. It appears to work at first, but the solution you merged is not a proper fix. 

The best way I can show that this fix isnt correct is if you look at the package qrcode-generator, which is what this package is built on, type in the exact same URL, with the same error correction, with type 0 on this package and on qrcode-generator, the QRs are completely different. You can try it here: https://kazuhikoarase.github.io/qrcode-generator/js/demo/

I have this issue fixed in a fork if you are interested. 

Would love to hear your thoughts.

**Comment by kozakdenys** [comment]
Hi @NickStull, thank you for raising this question. I want to explain what's been happening with this project.

When I started it, I didn't expect it to grow so much. I'm sorry that the community grew without me.

I was going through a tough time and was very focused on my job. Everything around me was draining all my energy and leaving me with little desire to work on anything else, including this project.

Now, I've decided to stop working  9 to 5 job and focus on things I truly enjoy. To try to collect some kind of donations I have decided to develop plugins for qr-code-stylin. Since I didn't find a suitable service for licensing plugins, I created a separate.

The paid plugin doesn't mean I’ll be focusing only on paid features. It means I’m taking more responsibility for this project. I plan to continue delivering free features as well. My idea is to make some niche features paid, as a way to gather donations.

I also plan to find some volunteers to help with admin here, so we can avoid the issues we've had in the past.

@NickStull, I saw your emails—sorry I didn't reply earlier. I’ve merged https://github.com/kozakdenys/qr-code-styling/pull/110, but it still seems to have some issues.

**Comment by kozakdenys** [comment]
@NickStull about closed PRs. I see two https://github.com/kozakdenys/qr-code-styling/pull/185 and https://github.com/kozakdenys/qr-code-styling/pull/141. It was accidentally as I deleted released branch and didn't see there were related PRs. I will reopen them.
If you see some other, please ping me

**Comment by NickStull** [comment]
Thank you so very much for responding. I appreciate your honesty. 

> It means I’m taking more responsibility for this project.

I am happy to hear this and do hope this is true.

I will do my best to add a PR. Though I have added so many fixes and new features to my fork, that It might be tough to decipher what was the actual fix. I will take a look.

**Comment by kozakdenys** [comment]
Hi @NickStull, I have merged fix for dots rotation issue in the [v1.7.1](https://github.com/kozakdenys/qr-code-styling/releases/tag/v1.7.1)
Also, I would like to close this issue and move discusion about paid plugins to [discussions](https://github.com/kozakdenys/qr-code-styling/discussions/225) section
